version: '2.4'

volumes:
  octoprint-docker:
services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
    # find usb devices with cmd 'ls /dev | grep -i "usb"'
    devices:
      - /dev/ttyUSB0 
    volumes:
      - octoprint-docker:/home/octoprint/.octoprint
